
# [[file:~/git/bitbucket-grettke/hardware/apple/macbookpro/c02m/provisioning.org::*Dropbox][Dropbox:1]]

Sign in.
In Login Items, start Dropbox.
When on highspeed, just sync everything after copying locally of course.
When on lowspeed, just sync required.

# Dropbox:1 ends here

# [[file:~/git/bitbucket-grettke/hardware/apple/macbookpro/c02m/provisioning.org::*Little%20Snitch][Little\ Snitch:1]]

As of writing, the installer just gets downloaded and you need to run it like
this:

#+begin_src sh
open /opt/homebrew-cask/Caskroom/little-snitch/3.5.1/Little Snitch Installer.app/
#+end_src

Typical usage is to grant every program full access for any connection, forever,
until there is a reason not to do so.

- Gen
  - Show inactive warning
  - Silent mode: no
  - Show status in menu bar.
- Alert:
  - Detail level: Show full details
  - No: Confirm automatically
  - NO: Confirm with return and escape.
- Monitor:
  - Keyboard shortcut: On
  - Show network activity in menu bar.
    - Show data rates numerically. Monochrome.
  - Show auto when mouse enters. Hide in 2s.
- APS
  - No: Enable automatic profile switching
  - Yes: Save geolocation of networks.
- Security
  - Allow rules and profile edit.
  - Allow profile switch.
  - Allow preference editing
  - Respect privacy.
- Advanced
  - Approve rules automatically.
Update
  - Automatically check for updates daily

# Little\ Snitch:1 ends here

# [[file:~/git/bitbucket-grettke/hardware/apple/macbookpro/c02m/provisioning.org::*Chrome][Chrome:1]]

Sign into Chrome. Let the settings sync. All the JS disabling stuff needs
you to approve it. It is irritating. You always forget to approve it and make
it worse. Disable ScriptSafe right away. Turn it on as needed.

# Chrome:1 ends here

# [[file:~/git/bitbucket-grettke/hardware/apple/macbookpro/c02m/provisioning.org::*Firefox][Firefox:1]]

Install the standard plugins: NoScript, Blur.

# Firefox:1 ends here

# [[file:~/git/bitbucket-grettke/hardware/apple/macbookpro/c02m/provisioning.org::*Filezilla][Filezilla:1]]

Set up Filezilla for WnW.

# Filezilla:1 ends here

# [[file:~/git/bitbucket-grettke/hardware/apple/macbookpro/c02m/provisioning.org::*Skype][Skype:1]]

Log in automatically. Don't grant access to contacts.
Preferences General. Never set my status away. Don't show birthday notifications. Don't always keep Skype up to date.
Messaing: Don't use larg emotions. Use compact chat style. Don't show when I am typing.
Notifications: Do not notify when I sign in or out, and others, and when they become
available do nothing.
Advanced: Display technical call information yes. Do not collect
call information.
Login Items, add Skype in here.

# Skype:1 ends here

# [[file:~/git/bitbucket-grettke/hardware/apple/macbookpro/c02m/provisioning.org::*SourceTree][SourceTree:1]]

Log into SourceTree.
Let it scan the BitBucket folder to add those projects to SourceTree.
Preferences.
General: Disallow SourceTree from modifying yoru global Git config file
Diff: Set font to DJSM 14.
Manually:
- Go through the licensing process
- Old app just let you type it into the GUI, not seeing it here now

# SourceTree:1 ends here

# [[file:~/git/bitbucket-grettke/hardware/apple/macbookpro/c02m/provisioning.org::*Racket][Racket:1]]

racket --version

# Racket:1 ends here

# [[file:~/git/bitbucket-grettke/hardware/apple/macbookpro/c02m/provisioning.org::*Freemind][Freemind:1]]

Run it.

# Freemind:1 ends here

# [[file:~/git/bitbucket-grettke/hardware/apple/macbookpro/c02m/provisioning.org::*VIM%20&%20MacVIM][VIM\ &\ MacVIM:1]]

Copy over my .vimrc, once one exists.
Run it.

# VIM\ &\ MacVIM:1 ends here

# [[file:~/git/bitbucket-grettke/hardware/apple/macbookpro/c02m/provisioning.org::*Virtualbox][Virtualbox:1]]

Boot up at least one Vagrant box using Virtualbox to make sure it is happy.
The directions are with Vagrant.

# Virtualbox:1 ends here

# [[file:~/git/bitbucket-grettke/hardware/apple/macbookpro/c02m/provisioning.org::*VMWare%20Fusion][VMWare\ Fusion:1]]

License it.
Boot up at least one Vagrant box using VMWare Fusion to make sure it is happy.
The directions are with Vagrant.

# VMWare\ Fusion:1 ends here

# [[file:~/git/bitbucket-grettke/hardware/apple/macbookpro/c02m/provisioning.org::*Libre%20Office][Libre\ Office:1]]

Run it.

# Libre\ Office:1 ends here

# [[file:~/git/bitbucket-grettke/hardware/apple/macbookpro/c02m/provisioning.org::*Kindle][Kindle:1]]

Sign in. Make sure it works. Download everything so it is there.
You can see files downloaded versus avalable to be sure. Or not.
The upside is reading without Internet connectivity.

# Kindle:1 ends here

# [[file:~/git/bitbucket-grettke/hardware/apple/macbookpro/c02m/provisioning.org::*VLC][VLC:1]]

Run it.

# VLC:1 ends here

# [[file:~/git/bitbucket-grettke/hardware/apple/macbookpro/c02m/provisioning.org::*Part%20A][Part\ A:1]]

Remember to run these. Just do a version check or something.

# Part\ A:1 ends here

# [[file:~/git/bitbucket-grettke/hardware/apple/macbookpro/c02m/provisioning.org::*R][R:1]]

I haven't used R in a long time but I want to get it set up right again.
Link my configs from ~/ into where they live now.
This installer asks for my password, which halts the install. How will I deal
with this?
There is a =.Rinstall= file in my setup to get all of the packages installed. Be s
sure to run that, too. All of my notes live in R.org already.

# R:1 ends here

# [[file:~/git/bitbucket-grettke/hardware/apple/macbookpro/c02m/provisioning.org::*R%20Studio][R\ Studio:1]]

This doesn't need any config I think.
Run it.

# R\ Studio:1 ends here

# [[file:~/git/bitbucket-grettke/hardware/apple/macbookpro/c02m/provisioning.org::*Vagrant][Vagrant:1]]

Install the VMWare provider for Vagrant and then license it.

Remember to [[http://docs.vagrantup.com/v2/other/debugging.html][log]] appropriately.

It goes something like this:

#+begin_src sh
vagrant plugin install vagrant-vmware-fusion
mkdir ~/.vagrant
cd ~/.vagrant
# copy that license file in there
vagrant plugin license vagrant-vmware-fusion license.lic
#+end_src

Test out VirtualBox box:

#+begin_src sh
cd ~/tmp
vagrant init hashicorp/precise32
vagrant up --provider virtualbox
#+end_src

The first time I tried this, it failed. I restarted OSX. Then it worked.

Test out VMWare:

#+begin_src sh
cd ~/tmp
vagrant init chef/ubuntu-14.04
vagrant up
#+end_src

# Vagrant:1 ends here

# [[file:~/git/bitbucket-grettke/hardware/apple/macbookpro/c02m/provisioning.org::*Vagrant%20Manager][Vagrant\ Manager:1]]

- Terminal Preference: Terminal
- Status Bar Icon Theme: Clean
- Launch at login: Yes
- Following settings: No
- Refresh every: 5 seconds
- Following settings: No
- Allowed Updates: stable
- Send anonymous profile data: Yes

# Vagrant\ Manager:1 ends here
