# [[file:~/git/github/osx-provision/El-Capitan/provisioning.org::org_gcr_2017-05-12_mara_F8442214-41F6-4F42-9B5C-B4BBDF9A840A][org_gcr_2017-05-12_mara_F8442214-41F6-4F42-9B5C-B4BBDF9A840A]]
* Carbon Copy Cloner

*Only install on hosts*

- Steps
  - Install version 4
  - License it
  - Preferences \rarr Notifications \rarr Show CCC icon in the menu bar
- Application Configuration
  - Mirror the storage partition
    - Identify and drag \rarr storage partition
    - Identify and drag \rarr destination partition
    - Schedule the task
      - Daily
      - 5:30pm
      - Defer to other writers
      - If the external is not mounted then run it when it returns
    - Before this task runs
      - Pull Git repos
  - Mirror the boot partition
    - Identify and drag \rarr boot partition
    - Identify and drag \rarr destination partition
    - Save it
    - Modify the storage backup task to run /this/ task upon completion

* VMWare

*Only install on hosts*

- On a host: License it

* Vagrant

Install the VMWare provider for Vagrant and then license it.

Remember to [[http://docs.vagrantup.com/v2/other/debugging.html][log]] appropriately.

It goes something like this:

#+begin_src sh
vagrant plugin install vagrant-vmware-fusion
mkdir ~/.vagrant
cd ~/.vagrant
# copy that license file in there
vagrant plugin license vagrant-vmware-fusion license.lic
cd
rm -rf ~/.vagrant
#+end_src

Verify the plugin is licensed and happy:

#+BEGIN_SRC sh
vagrant plugin list
#+END_SRC

Test out VirtualBox box:

#+begin_src sh
cd ~/tmp
mkdir vgtest
cd vgtest
vagrant init hashicorp/precise64
vagrant up --provider virtualbox
#+end_src

The first time I tried this, it failed. I restarted OSX. Then it worked.

Test out VMWare. The default provider is vmware, so don't have to specify
provider.

#+begin_src sh
cd ~/tmp/vgtest
vagrant up
#+end_src

* Packer

- Nothing at this time

* iPartition

- License it
# org_gcr_2017-05-12_mara_F8442214-41F6-4F42-9B5C-B4BBDF9A840A ends here
