* Configuration
:PROPERTIES:
:ID:       2C0462E0-0E79-436E-9CBF-58C8DAF40CB1
:END:
** Common
:PROPERTIES:
:ID:       597AA955-95B9-4B69-9FB3-A2DFA768CACF
:END:
*** Manual
:PROPERTIES:
:header-args: :noweb-ref configuration-common-manual
:ID:       6507AFFC-5F3D-40D7-AA9A-53384A03EA0B
:END:

* Configuration
:PROPERTIES:
:ID:       262EEA68-1753-489D-A3BE-672C162CD356
:END:
** Common
:PROPERTIES:
:ID:       372CA3F6-90BB-48B0-A181-7866D1846F92
:END:
*** Manual
:PROPERTIES:
:ID:       BF5455FF-FABE-4A6D-B3B9-685DDDB83D09
:HEADER-ARGS: :noweb-ref configuration-common-manual
:END:

#+NAME: 639707FE-FE60-439E-A8C8-9FBD9936D1C4
#+BEGIN_SRC org
- Re-image your box
  - Host :: ~PHOSDI~
  - Guest :: ~IOSXECA~
- During configuration log into the App Store
- Make a user named ~gcr~ and choose an avatar
- Mouse
  - Host :: Connect Bluetooth mouse
  - Mke the mouse slow
- Host :: Reconfigure control keys
- Host :: Maximize resolution
- Host :: Show Keychain Access in Menubar
- Screensaver: Flurry, 10m
- Host :: Add printer
- Energy saver
  - Host :: do
    - On power, Computer sleep never, Screen sleep 15m, never auto sleep
      when display is off
    - On battery, Screen sleep 5m
      - Don't slightly dim the display on battery power
  - Guest :: Computer sleep never, Screen sleep 15
- Volume
  - Show volume in menubar
- Finder
  - Preferences
    - Favorites
      - <Home>
    - Devices
      - <Computer>
- Host :: Install Karabiner, allow, Change Return Key, Return to Option_L + When you type Return only
- Host :: Install VMWare Fusion Professional
#+END_SRC
*** Automated
:PROPERTIES:
:ID:       8CFB1149-4FB5-49EA-8037-BD25E71BDB14
:END:
**** Software
:PROPERTIES:
:ID:       5DB05063-0CA4-457A-A860-948F8957DD67
:END:
**** Settings
:PROPERTIES:
:ID:       7507CE02-9156-4748-A621-2CF51241B95E
:END:
***** Machine
:PROPERTIES:
:ID:       44A4C35C-E27A-462F-BBB2-A178F70194D8
:HEADER-ARGS: :noweb-ref configuration-common-automated-settings-machine
:END:

This script should be idempotent.

Aggressively debug.
#+NAME: C3D25C79-DF2D-4A1D-AE4F-16F20395AA95
#+BEGIN_SRC sh
set -x
#+END_SRC

Grant privileges.
#+NAME: EB44FB31-2B26-436C-89F3-E58B59450F87
#+BEGIN_SRC sh
sudo -v
#+END_SRC

Set the computer's "names". There are 3 resources ([[http://ilostmynotes.blogspot.com/2012/03/computername-vs-localhostname-vs.html][1]], [[http://osxdaily.com/2012/10/24/set-the-hostname-computer-name-and-bonjour-name-separately-in-os-x/][2]], [[http://hack.org/mc/writings/mac-survival.html][3]]) that I used to make
sense of the different names. It is simple, and new to me.

Originally I set every name to the same value. Doing so didn't result in
warnings but it did result in an incorrect "Computer Name" and
"Local Host Name". Based on that experience, I'm going to give names using this
strategy to name machines now:

- HostName
  - All lower case
  - <Logical name>-<UUID>.<org|vm>
- LocalHostName
  - All lower case
  - <Logical name>-<UUID>
- NetBIOS
  - All lower case
  - <Logical name>-<UUID>
- ComputerName
  - "<Logical name> (<UUID>)"

Defining this naming approach helped me learn more about the intent of the
name and what I wanted from them.

#+NAME: 291FDE06-DF44-4156-A013-B763A8727B00
#+BEGIN_SRC sh
sudo scutil --set HostName ""
echo "Enter HostName (plain old hostname): "
read vhn
sudo scutil --set HostName $vhn
sudo scutil --set LocalHostName ""
echo "Enter LocalHostName (name for Bonjour services): "
read vlhn
sudo scutil --set LocalHostName $vlhn
sudo defaults delete 'com.apple.smb.server' NetBIOSName
read "Enter NetBIOSName (name that Windows boxes will see): "
read vnbn
sudo defaults write 'com.apple.smb.server' NetBIOSName -string $vnbn
sudo scutil --set ComputerName ""
echo "Enter ComputerName (human friendly GUI name): "
read vcn
sudo scutil --set ComputerName $cn
#+END_SRC

Display login window as name and password.
#+NAME: 2F39C8B9-CA25-4C94-8E77-AD348D5235A9
#+BEGIN_SRC sh
sudo defaults write /Library/Preferences/com.apple.loginwindow.plist SHOWFULLNAME -bool true
#+END_SRC

Login message.
#+NAME: 850816F3-B82E-4EE0-9895-6E99CB6A7593
#+BEGIN_SRC sh
sudo defaults write /Library/Preferences/com.apple.loginwindow.plist LoginwindowText -string "
All creativity is an extended form of a joke.
          — Alan Kay"
#+END_SRC

Disable Gatekeeper.
#+NAME: DBE84671-1CC0-4DBA-AC7C-72F9EAC857A0
#+BEGIN_SRC sh
sudo spctl --master-disable
#+END_SRC

** Host
:PROPERTIES:
:ID:       4176F379-79B3-466F-A689-11701A0432EF
:END:
*** Manual
:PROPERTIES:
:header-args: :tangle configuration-host-manual.org :noweb yes
:ID:       AD976F50-9B8A-4B07-ABA6-B00FE0081E90
:END:

Perform the common steps.
#+NAME: 2C87821E-2E7E-42F2-8512-96AE52230752
#+BEGIN_SRC org :noweb yes
<<configuration-common-manual>>
#+END_SRC
*** Automated
:PROPERTIES:
:ID:       D1DA1C61-8183-4A22-8AE6-0F6BE016A787
:END:
**** Software
:PROPERTIES:
:ID:       68C5F6B5-9D98-4562-92A2-BE3D5C52F76E
:END:
**** Settings
:PROPERTIES:
:ID:       D19C1E4F-7195-44AE-A3D1-1D48AAC91BD1
:END:
***** Machine
:PROPERTIES:
:header-args: :tangle configuration-common-automated-settings-machine.sh :tangle-mode: (identity #o755)
:ID:       41EB1F53-CDA3-4132-AED2-0DB1A4B0AF0A
:END:

Perform the common steps.
#+NAME: 18A5D7F2-74AA-48C4-89F8-C2C567FBE78A
#+BEGIN_SRC org
<<configuration-common-automated-settings-machine>>
#+END_SRC
***** User
:PROPERTIES:
:ID:       F8CA72C3-AB98-4998-B19B-10F617620792
:END:
