* Goal
:PROPERTIES:
:ID:       572893EF-E80B-411B-9355-8CAB3DB23C27
:END:

** Desire
:PROPERTIES:
:ID:       17BA9F22-3B3E-427E-AC9B-0DF8D10BFD32
:END:

- To quickly and easily
  - Explore cognitive spaces using operating systems and software
  - Try, fail, learn, improve, and repeat
  - For expensive operations measured in time and complexity
    - Minimize their execution time
      - Central Processing Unit (CPU)
      - Input/Output (IO)
    - Rebound from failure
  - Share

** Satisfaction
:PROPERTIES:
:ID:       77F8D1AF-B388-4512-B9C2-79F97533CC88
:END:

- First-class support for OS X, Windows, Linux and all of their software
- Manage machines as easily and flexibly as you would with version control
- Use the fastest devices possible for every operation
- First class operating system image management
- Virtual machines (VM)

** Decision
:PROPERTIES:
:ID:       643E82D4-08E8-40B5-9006-3936A0775A35
:END:

- Current:
  - Macintosh Computer (Mac)
  - OS X
  - VMWare Fusion Professional
- With /Best/:
  - Solid State Disk (SSD)
  - RAM
  - CPU count and speed

** Lessons Learned
:PROPERTIES:
:ID:       0D8B4834-2E1E-4F1A-9299-5948A1FFAC55
:END:

- Verify easily verifiable operations
  - Installation scripts often reveal new information
- Either name things with a meaningful name or a 6 digit UUID from
  [[https://www.uuidgenerator.net/][Online UUID Generator]]
- Evidence based; no fantasy or delusion
  - Decide using experience; in absence make a best decision and move on
- "Thinking ahead" is crippling
- Version after expensive operations
  - Can always delete them later
- Don't go to sleep in the middle of configuration sections
- Get the fastest Internet sold before starting
- Remember that Control-Command-F pressed inside of a host works against VMWare
  to go to and from full-screen.
- Snapshot frequently; you never know how things will go
  - You will forget to do this
  - You will only care after something got wrecked
- VMWare's folder sharing
  - Works perfectly for sharing between two guests a lot of the time. When it
    quits working I log in and out of one of the guests and it works again
    - Happens often
  - Is happy with Finder and unhappy with Eshell, so don't use Eshell in shared
    directories. They just stop working.
- Java
  - Sometimes the installation directory includes the build number. Sometimes
    it does not.
- Writing 100% automated idempotent scripts is worth the effort
  - It is not worth the effort for theoretical reasons because it is usually
    faster to do it by hand. The first 2 or 3 times you perform a task, it is
    slow, and then you figure it how to do it all correctly and then you can
    perform it quickly. You might ask yourself "If I can do it this quickly then
    why bother automated it?" because of the extra effort. That is a good
    question. When you are doing it, it is faster to do it by hand. Here is the
    problem that I ran into: you make mistakes that you find long after the
    set up. The /right/ thing to do is to correct the documentation/scripts and
    then rebuild the image. If you left manual steps then you have to do that
    work all over again. I know this seems obvious, but at the time, it didn't
    seem worth the effort of automating everything. Now much later, I'm left
    with a system imaged somewhat differently than the documentation. It is
    worth the effort to automate everything.

* Preparation
:PROPERTIES:
:ID:       1BF6D42F-2F80-467E-B75C-DB2C88F0B4BE
:END:

** External Drive
:PROPERTIES:
:ID:       9EC3FF1F-8416-449D-8860-3B4ABCEBB09B
:END:

Get a 7200RPM 1TB external disk drive with USB3 or Lightning.

Create a partition named =Storage= that is at least 100GB. The =EXT:= naming
convention is to indicate that it lives on an external device. This is helpful
to make sense of partitions there versus on the Macintosh HD. That is not part
of the name of the partition itself. I'll use that naming also to indicate
computers that contain a single disk drive.

** Software
:PROPERTIES:
:ID:       3BC9B846-919F-4395-8926-8C2AABB0FF6A
:END:
*** Carbon Copy Cloner (CCC)
:PROPERTIES:
:ID:       93F797EC-1166-4667-A2ED-C8251CB9998A
:END:

[[https://bombich.com/][Purchase]] the latest version that supports El Capitan. Download it along with the
license to =EXT:Storage=. Install it on the =Support Computer=.
*** VMWare Fusion
:PROPERTIES:
:ID:       B846A16A-4E1C-4968-B303-301923989BD8
:END:

[[https://www.vmware.com/products/fusion][Purchase]] a copy and download it to =EXT:Storage=. Download your license key.

** Support Computer
:PROPERTIES:
:ID:       74903C97-520F-4FE1-B2AA-09F1DAB976D7
:END:

Keep a working Mac nearby. You will use it to work with the contents of
your Git repositories, research configuration steps, and rest easy knowing that
you've always got a working machine.

Make sure that it has Internet access and download all of your Git repositories
required for configuring these machines.

Don't try use your host computer for this role by booting it to an external
drive; it is too easy to confuse partitions and what you are doing.

Use CCC to clone this Mac's partition, =Support:Macintosh HD=, to a partition on
=EXT=. The easiest thing to do is to connect =EXT=
to =Support Computer=. Create a new partition big enough to hold it and perform
the clone. Name it =EXT:Utility=. Reboot to it to test it.

** Host Computer: 44fad7
:PROPERTIES:
:ID:       EE23E7E0-4BAC-4B57-96EA-764F84A2F054
:END:

- Collect the Pristine Host Operating System Image (PHOSI)
  - Pristine means that it has never been logged into or configured
  - Has the latest OS X on it with at least the second fix pack or later
  - Verify that it contains Recovery Partition for that OS X on the disk
    - If the imaging takes less than 10 minutes then they didn't include the
      Recovery Partition
  - You can easily get this from an appointment at the Genius Bar
- Create the Pristine Host Operating System Disk Image (PHOSDI)
  - Take your Mac home
  - Boot from =EXT:Utility=
  - Use CCC
    - From the host computer's =PHOSI=, =Host:Macintosh HD=
    - To
      - A new =PHOSDI=; *read-only* and *compressed* disk image
      - Located on =EXT:Storage=
    - Execute the imaging task
- Test =PHOSDI=
  - Boot into =Host:Macintosh HD=, configure it
  - Boot into =EXT:Support= and re-image =Host:Macintosh HD= from =PHOSDI=
  - Boot into =Host:Macintosh HD=
    - It should appear pristine, you need to enter all of the installation
      information again. This will be re-imaged again soon so don't worry
      about this.
  - Copy =EXT:Storage PHOSDI= to =Host:Storage=
- Create the =Host:Utility= partition using =PHOSDI=
  - Boot into =EXT:Support=
  - Create 1 new partition on =Host=, named =Utility=: 16GB
    - Now there are 3: =Macintosh HD=, =Support=, and =Utility=
  - Verify that you can
    - Boot into =Host:Support=
    - Install CCC
    - Access the =Storage= partition
      - CCC images
      - Disk images
      - Software
      - Scripts

* Host Configuration
:PROPERTIES:
:ID:       29CB47C1-03D5-4495-8182-486513A2079C
:END:

** Starting Point
:PROPERTIES:
:ID:       B4E2D4A0-1525-40D3-AB8D-345494B2403D
:END:

- Image your machine using =PHOSDI=

** Manual Steps
:PROPERTIES:
:ID:       6507AFFC-5F3D-40D7-AA9A-53384A03EA0B
:END:

Steps unique to the host are indicated.

- During configuration personalize/configure/install nothing but timezone
- Make a user named =sysop=, System Operator
- Host :: Bluetooth mouse
- Slowish mouse
- Host :: Swap control keys
- Host :: Install Karabiner, allow, Change Return Key, Return to Option_L + When you type Return only
- Host :: Maximize resolution
- Show Keychain Access in Menubar
- Screensaver: Flurry, 10m
- Host :: Add printer
- Energy saver
  - Host :: On power, 15m, never auto sleep when display is off
  - Guest :: Computer sleep 15, Screen sleep 15
- Install Spectacle, allow, start at boot
- Host :: Install VMWare Fusion Professional

** Automated Steps
:PROPERTIES:
:ID:       E72C95F4-9D62-4864-9BD5-441C7635BAA4
:header-args: :epilogue "read -p \"Press [Enter] key to continue...\""
:END:

This file creates two script files:
- osx-per-machine.sh :: Provisions a single machine
- osx-per-user.sh :: Provisions a single user on a machine

They are generalized and re-usable scripts. The points in this document that
refer to "provsioning" mean to do so using these scripts.

*** Per Machine
:PROPERTIES:
:tangle:   ./osx-per-machine.sh
:tangle-mode: (identity #o755)
:ID:       0B05FB9A-08DF-448C-AE2E-0715B0B217F8
:END:

This script should be idempotent.

Aggressively debug.
#+NAME: C3D25C79-DF2D-4A1D-AE4F-16F20395AA95
#+BEGIN_SRC shell
set -x
#+END_SRC

Set the computer's "names". There are 3 resources ([[http://ilostmynotes.blogspot.com/2012/03/computername-vs-localhostname-vs.html][1]], [[http://osxdaily.com/2012/10/24/set-the-hostname-computer-name-and-bonjour-name-separately-in-os-x/][2]], [[http://hack.org/mc/writings/mac-survival.html][3]]) that I used to make
sense of the different names. It is simple, and new to me.

Originally I set every name to the same value. Doing so didn't result in
warnings but it did result in an incorrect "Computer Name" and
"Local Host Name". Based on that experience, I'm going to give names using this
strategy to name machines now:

- HostName
  - TLD
    - For virtual machines :: vm
    - For everything else :: org
  - SLD
    - Logical name and UUID separated by a dash, all lower case,
- LocalHostName
  - Logical name and UUID separated by a dash, all lower case
- ComputerName
  - Logical name, a space, and UUID surrounded by round parentheses;
    all properly cased

#+NAME: 291FDE06-DF44-4156-A013-B763A8727B00
#+BEGIN_SRC shell
echo "Enter HostName: "
read vhn
echo "Enter LocalHostName: "
read vlhn
echo "Enter ComputerName: "
read vcn
sudo scutil --set HostName $vhn
sudo scutil --set LocalHostName $vlhn
sudo scutil --set ComputerName $cn
#+END_SRC

Display login window as name and password.
#+NAME: 2F39C8B9-CA25-4C94-8E77-AD348D5235A9
#+BEGIN_SRC shell
sudo defaults write /Library/Preferences/com.apple.loginwindow.plist SHOWFULLNAME -bool true
#+END_SRC

Login message.
#+NAME: 850816F3-B82E-4EE0-9895-6E99CB6A7593
#+BEGIN_SRC shell
sudo defaults write /Library/Preferences/com.apple.loginwindow.plist LoginwindowText -string "
All creativity is an extended form of a joke.
          — Alan Kay"
#+END_SRC

Disable Gatekeeper.
#+NAME: DBE84671-1CC0-4DBA-AC7C-72F9EAC857A0
#+BEGIN_SRC shell
sudo spctl --master-disable
#+END_SRC

*** Per User
:PROPERTIES:
:tangle:   ./osx-per-user.sh
:tangle-mode: (identity #o755)
:ID:       E9F72C01-7B0C-4714-9661-B7D75F98C56E
:END:

This script should be idempotent.

Aggressively debug.
#+NAME: A275F237-6C96-481A-AFD5-413933B3036E
#+BEGIN_SRC shell
set -x
#+END_SRC

- These commands are all [[https://github.com/kitchenplan/chef-osxdefaults/tree/master/recipes][copied]]
  - Including the documentation
  - Some of them have corrections and changes

***** Globals, Logical or Literal
:PROPERTIES:
:ID:       EC01CF33-40EE-4F63-8A27-A88DE32FC557
:END:

Set background.
#+NAME: 6755B45A-4331-4CA4-89D5-7A5906C3966A
#+BEGIN_SRC shell
cd ~/Pictures/
curl -O http://www.wisdomandwonder.com/wordpress/wp-content/uploads/2015/02/M101-ORG.jpg
sqlite3 ~/Library/Application\ Support/Dock/desktoppicture.db "update data set value = '~/Pictures/M101-ORG.jpg'";
#+END_SRC

Set default volume.
#+NAME: 57F27EEA-630B-4CB4-9A04-27091C4AD4CB
#+BEGIN_SRC shell
osascript -e 'set volume output volume 50'
#+END_SRC

Disable auto-correct.
#+NAME: 02346DB0-0D1F-4A80-89ED-C8B723C05BB6
#+BEGIN_SRC shell
defaults write 'NSGlobalDomain' NSAutomaticSpellingCorrectionEnabled -bool false
#+END_SRC

Expand print panel by default.
#+NAME: 207B6C0E-E636-4FAB-A859-6E3CA370C40E
#+BEGIN_SRC shell
defaults write 'NSGlobalDomain' PMPrintingExpandedStateForPrint -bool true
defaults write 'NSGlobalDomain' PMPrintingExpandedStateForPrint2 -bool true
#+END_SRC

Expand save panel by default.
#+NAME: FBAD5CA1-F984-46AE-940D-90B1FC6C8454
#+BEGIN_SRC shell
defaults write 'NSGlobalDomain' NSNavPanelExpandedStateForSaveMode -bool true
defaults write 'NSGlobalDomain' NSNavPanelExpandedStateForSaveMode2 -bool true
#+END_SRC

Automatically quit printer app once the print jobs complete.
#+NAME: F6899984-2233-4027-BBEF-1005657C7B5E
#+BEGIN_SRC shell
defaults write 'com.apple.print.PrintingPrefs' 'Quit When Finished' -bool true
#+END_SRC

Add battery percentage in menubar.
#+NAME: 8351B207-A376-4149-A876-4E3E8CE06732
#+BEGIN_SRC shell
defaults write 'com.apple.menuextra.battery' ShowPercent -bool true
#+END_SRC

Add date in menubar clock.
#+NAME: 3525C306-F373-4146-8579-60E38D765425
#+BEGIN_SRC shell
defaults write 'com.apple.menuextra.clock' DateFormat -string "EEE MMM d  HH:mm"
#+END_SRC

Prevent Time Machine from prompting to use new hard drives as backup volume.
#+NAME: B7665462-71BC-4929-86C9-4766C3BAA9DB
#+BEGIN_SRC shell
defaults write 'com.apple.TimeMachine' DoNotOfferNewDisksForBackup -bool true
#+END_SRC

Avoid creating .DS_Store files on network volumes.
#+NAME: EE3BD935-46A0-425C-9DAB-0CB341D5E501
#+BEGIN_SRC shell
defaults write 'com.apple.desktopservices' DSDontWriteNetworkStores -bool true
#+END_SRC

Save to disk (not to iCloud) by default.
#+NAME: 526B969F-94AD-441B-8F5D-52141EDA0507
#+BEGIN_SRC shell
defaults write 'NSGlobalDomain' NSDocumentSaveNewDocumentsToCloud -bool false
#+END_SRC

Increase window resize speed for Cocoa applications.
#+NAME: 16416BAF-CFEE-43E2-9B6B-C2B85C73D627
#+BEGIN_SRC shell
defaults write 'NSGlobalDomain' NSWindowResizeTime -float 0.001
#+END_SRC

Use the Graphite theme.
#+NAME: 8D12169D-8717-46D4-920E-D4C322C4458E
#+BEGIN_SRC shell
defaults write 'NSGlobalDomain' AppleAquaColorVariant -int 6
#+END_SRC

Use dark menu bar and Dock
#+NAME: 337E87AE-39CC-41F5-B115-11B994E125B5
#+BEGIN_SRC shell
defaults write 'NSGlobalDomain' AppleInterfaceStyle -string Dark
#+END_SRC

Disable the “Are you sure you want to open this application?” dialog.
#+NAME: F89AEE9E-D5D6-4EF9-9914-CE2C3AE53B9B
#+BEGIN_SRC shell
defaults write com.apple.LaunchServices LSQuarantine -bool false
#+END_SRC

Display ASCII control characters using caret notation in standard text views.
Try e.g. `cd /tmp; unidecode "\x{0000}" > cc.txt; open -e cc.txt`.
#+NAME: A2CDF5C4-9239-47AD-9978-09582362316C
#+BEGIN_SRC shell
defaults write NSGlobalDomain NSTextShowsControlCharacters -bool true
#+END_SRC

Disable automatic termination of inactive apps.
#+NAME: 4FDA48E0-AC9B-48B9-A09D-E54F72787F64
#+BEGIN_SRC shell
defaults write NSGlobalDomain NSDisableAutomaticTermination -bool true
#+END_SRC

Disable the crash reporter.
#+NAME: E102244A-C691-4E62-BE68-3BF1EB8D340F
#+BEGIN_SRC shell
defaults write com.apple.CrashReporter DialogType -string "none"
#+END_SRC

Set Help Viewer windows to non-floating mode.
#+NAME: FC22C88E-44B4-4C50-B00A-82DB0DCDB519
#+BEGIN_SRC shell
defaults write com.apple.helpviewer DevMode -bool true
#+END_SRC

Restart automatically if the computer freezes.
#+NAME: F3347821-BEB6-4D91-8ADC-D968F825D491
#+BEGIN_SRC shell
sudo systemsetup -setrestartfreeze on
#+END_SRC

Check for software updates daily, not just once per week.
#+NAME: B0166A42-EB93-444D-ACDA-A0E2AED02543
#+BEGIN_SRC shell
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1
#+END_SRC

Disable Notification Center and remove the menu bar icon.
#+NAME: 493ABAF1-8385-4ADF-90C3-B61699A5603B
#+BEGIN_SRC shell
launchctl unload -w /System/Library/LaunchAgents/com.apple.notificationcenterui.plist 2> /dev/null
#+END_SRC

Disable smart quotes as they’re annoying when typing code.
#+NAME: 1450BB2D-B822-48D3-ADC8-46FFF00B730C
#+BEGIN_SRC shell
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
#+END_SRC

Disable smart dashes as they’re annoying when typing code.
#+NAME: B829AB6A-309B-406F-A51F-2CF38C183210
#+BEGIN_SRC shell
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false
#+END_SRC

***** Hardware
:PROPERTIES:
:ID:       F6533ADA-A21F-49E7-8DD7-4447CF69A528
:END:

Disable press-and-hold for keys in favor of key repeat.
#+NAME: 9078E7EB-65AE-4B8E-978A-E6687DB2C4EA
#+BEGIN_SRC shell
defaults write 'NSGlobalDomain' ApplePressAndHoldEnabled -bool false
#+END_SRC

Use all F1, F2, etc. keys as standard function keys.
#+NAME: 662F5288-F102-4FCA-B052-31933DFEFC0B
#+BEGIN_SRC shell
defaults write 'NSGlobalDomain' com.apple.keyboard.fnState -bool true
#+END_SRC

Increase sound quality for Bluetooth headphones/headsets.
#+NAME: 03E4D631-C6E3-4E4E-BCE9-BDB87D8549FD
#+BEGIN_SRC shell
defaults write com.apple.BluetoothAudioAgent "Apple Bitpool Min (editable)" -int 40
#+END_SRC

***** Dock
:PROPERTIES:
:ID:       B3122846-4906-4F7C-AD02-63A84B47A92D
:END:

Automatically hide and show the dock.
#+NAME: 44629106-AB81-4099-AAAE-2A1692110652
#+BEGIN_SRC shell
defaults write com.apple.dock autohide -bool true && killall Dock
#+END_SRC

Do not animate opening applications from the Dock.
#+NAME: 3A5370F0-1F37-47A9-8AD2-5A54F7BEBAF6
#+BEGIN_SRC shell
defaults write com.apple.dock launchanim -bool false && killall Dock
#+END_SRC

Enable highlight hover effect for the grid view of a stack.
#+NAME: 2E431E6C-083A-40C3-844A-187F6523CB77
#+BEGIN_SRC shell
defaults write com.apple.dock mouse-over-hilte-stack -bool true && killall Dock
#+END_SRC

Make Dock icons of hidden applications translucent.
#+NAME: 2E431E6C-083A-40C3-844A-187F6523CB77
#+BEGIN_SRC shell
defaults write com.apple.dock showhidden -bool true && killall Dock
#+END_SRC

Minimize to application.
#+NAME: 6AB142A8-9150-4B3B-8709-237D468212E0
#+BEGIN_SRC shell
defaults write com.apple.dock minimize-to-application -bool true && killall Dock
#+END_SRC

Move the Dock to the left side of the screen.
#+NAME: 7CF0E408-7318-4921-B8BE-F834C8A63BC7
#+BEGIN_SRC shell
defaults write com.apple.dock orientation -string left && killall Dock
#+END_SRC

Remove the animation when hiding/showing the dock.
#+NAME: 2250EED5-046B-4F55-B64E-04787C078F5B
#+BEGIN_SRC shell
defaults write com.apple.Dock autohide-time-modifier -float 0 && killall Dock
#+END_SRC

Remove the auto-hiding Dock delay".
#+NAME: CA55EDF7-AB57-450A-A80A-D9BCE9219951
#+BEGIN_SRC shell
defaults write com.apple.Dock autohide-delay -float 0 && killall Dock
#+END_SRC

Set the icon size of Dock items to 50 pixels.
#+NAME: C92642D8-BA50-46E4-B9D0-A0A7DEEAF0B9
#+BEGIN_SRC shell
defaults write com.apple.Dock tilesize -int 50 && killall Dock
#+END_SRC

Show indicator lights for open applications in the Dock.
#+NAME: 9402CBD6-530E-4832-8D6A-405EB9172F37
#+BEGIN_SRC shell
defaults write com.apple.Dock show-process-indicators -bool true && killall Dock
#+END_SRC

Wipe all (default) app icons from Dock.
#+NAME: 9402CBD6-530E-4832-8D6A-405EB9172F37
#+BEGIN_SRC shell
defaults write 'com.apple.dock' persistent-apps -array '' && killall Dock
#+END_SRC

Speed up Mission Control animations.
#+NAME: 2AEA50FA-CA94-438A-B82E-3B465CAA2E12
#+BEGIN_SRC shell
defaults write 'com.apple.dock' expose-animation-duration -float 0.1 && killall Dock
#+END_SRC

***** Finder
:PROPERTIES:
:ID:       E7984F15-4360-4F00-B754-CC00FC4D4124
:END:

Allow text selection in Quick Look.
#+NAME: A6759B25-1B21-40C2-A75C-B2DF18A3CAC1
#+BEGIN_SRC shell
defaults write 'com.apple.finder' QLEnableTextSelection -bool true && killall Finder
#+END_SRC

Automatically open a new Finder window when a volume is mounted.
#+NAME: DCDE10BB-3848-4C70-9B7A-8F5641950CCB
#+BEGIN_SRC shell
defaults write 'com.apple.frameworks.diskimages' auto-open-ro-root -bool true && killall Finder
defaults write 'com.apple.frameworks.diskimages' auto-open-rw-root -bool true && killall Finder
defaults write 'com.apple.finder' OpenWindowForNewRemovableDisk -bool true && killall Finder
#+END_SRC

Disable the warning before emptying the Trash.
#+NAME: 4647036E-8DB1-4119-B6D1-2028941B9A91
#+BEGIN_SRC shell
defaults write 'com.apple.finder' WarnOnEmptyTrash -bool false && killall Finder
#+END_SRC

Disable the warning when changing a file extension.
#+NAME: 00CEF20F-FDD2-464F-B8E4-968682A62B26
#+BEGIN_SRC shell
defaults write 'com.apple.finder' FXEnableExtensionChangeWarning -bool false && killall Finder
#+END_SRC

Set finder to display full path in title bar.
#+NAME: 1C946EE8-4D17-4D03-BF58-F2C5C1280739
#+BEGIN_SRC shell
defaults write 'com.apple.finder' _FXShowPosixPathInTitle -bool true && killall Finder
#+END_SRC

New Finder window shows the homefolder.
#+NAME: 85E615B8-24C6-4819-B437-BB1ED2384E82
#+BEGIN_SRC shell
defaults write 'com.apple.finder' NewWindowTarget -string PfHm && killall Finder
#+END_SRC

When performing a search, search the current folder by default.
#+NAME: FB3EFB97-6BEC-4BE4-B8D5-8EACD289CE66
#+BEGIN_SRC shell
defaults write 'com.apple.finder' FXDefaultSearchScope -string SCcf && killall Finder
#+END_SRC

Show all files in Finder.
#+NAME: 5F5E19CE-ECA4-4633-8C67-299C2237C7E2
#+BEGIN_SRC shell
defaults write 'com.apple.finder' AppleShowAllFiles -bool true && killall Finder
#+END_SRC

Show file extensions in Finder.
#+NAME: 7C10B346-5B87-456F-B424-1ED79C2ADE2B
#+BEGIN_SRC shell
defaults write 'com.apple.finder' AppleShowAllExtensions -bool true && killall Finder
#+END_SRC

Show path bar in Finder.
#+NAME: 69400DBC-BA03-4CB4-B724-BA22C070CB2B
#+BEGIN_SRC shell
defaults write 'com.apple.finder' ShowPathbar -bool true && killall Finder
#+END_SRC

Show status bar in Finder.
#+NAME: 6D032485-D6D0-47A4-9B14-06FE6FC0CB80
#+BEGIN_SRC shell
defaults write 'com.apple.finder' ShowStatusBar -bool true && killall Finder
#+END_SRC

Sidebar icon size Small.
#+NAME: 38B74BA0-FFCD-4E46-A1F0-BA839DF631DB
#+BEGIN_SRC shell
defaults write 'NSGlobalDomain' NSTableViewDefaultSizeMode -bool true && killall Finder
#+END_SRC

View style.
#+NAME: 17D25945-67E7-4F54-9DAA-C23FD89A2758
#+BEGIN_SRC shell
defaults write 'com.apple.Finder' FXPreferredViewStyle clmv && killall Finder
#+END_SRC

Finder: disable window animations and Get Info animations.
#+NAME: AF8A02A4-CFFC-4740-A6E9-3341F912906A
#+BEGIN_SRC shell
defaults write com.apple.finder DisableAllAnimations -bool true
#+END_SRC

Show icons for hard drives, servers, and removable media on the desktop.
#+NAME: 5F9ED39D-B319-46AE-B64F-F8CCE66C14CB
#+BEGIN_SRC shell
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true
#+END_SRC

***** Screen
:PROPERTIES:
:ID:       76D10582-3909-4CBB-9770-DF3D4F7C9DB0
:END:

Require password immediately after sleep or screen saver begins.
#+NAME: A73210E6-B619-4523-BD19-A5F8951E8495
#+BEGIN_SRC shell
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0
#+END_SRC

Disable shadow in screenshots.
#+NAME: E99413DF-0D11-4824-873D-3514F9333D6E
#+BEGIN_SRC shell
defaults write com.apple.screencapture disable-shadow -bool true
#+END_SRC

Save screenshots in PNG format.
#+NAME: EE876749-BDB9-466F-A0FC-567EBBF9C5C2
#+BEGIN_SRC shell
defaults write 'com.apple.screencapture' type -string png && killall SystemUIServer
#+END_SRC

Enable subpixel font rendering on non-Apple LCDs.
#+NAME: 66472988-E3AE-44D0-9423-17E9FEA0F5F1
#+BEGIN_SRC shell
defaults write 'NSGlobalDomain' AppleFontSmoothing -int 2
#+END_SRC

[[https://github.com/robb/.dotfiles/blob/master/osx/defaults.install][Via]]
#+NAME: 598BE517-CC5C-4D99-AD0B-41D2D906E376
#+BEGIN_SRC shell
mkdir -p ~/Screen\ Shots
defaults write com.apple.screencapture location ~/Screen\ Shots
#+END_SRC

***** Hotcorners
:PROPERTIES:
:ID:       14E7437D-7BE9-4149-818B-ADC7B145A822
:END:

- Possible values:
  - 0 :: no-op
  - 2 :: Mission Control
  - 3 :: Show application windows
  - 4 :: Desktop
  - 5 :: Start screen saver
  - 6 :: Disable screen saver
  - 7 :: Dashboard
  - 10 :: Put display to sleep
  - 11 :: Launchpad
  - 12 :: Notification Center

Top left screen corner → Mission Control.
#+NAME: 446CE2EF-BCBE-4D83-9ACC-2A1E2F91C64B
#+BEGIN_SRC shell
defaults write com.apple.dock wvous-tl-corner -int 2
defaults write com.apple.dock wvous-tl-modifier -int 0
#+END_SRC

Top right screen corner → Desktop.
#+NAME: FF4E8A69-A137-4E50-A4E4-59DA58A082B5
#+BEGIN_SRC shell
defaults write com.apple.dock wvous-tr-corner -int 4
defaults write com.apple.dock wvous-tr-modifier -int 0
#+END_SRC

Bottom left screen corner → Start screen saver.
#+NAME: 6A561511-8354-408E-8805-201BAAE80A04
#+BEGIN_SRC shell
defaults write com.apple.dock wvous-bl-corner -int 5
defaults write com.apple.dock wvous-bl-modifier -int 0
#+END_SRC

Bottom right screen corner → Application window.
#+NAME: 7C9DE1C5-BBF8-4D40-8FAC-E78D5B85231E
#+BEGIN_SRC shell
defaults write com.apple.dock wvous-bl-corner -int 3
defaults write com.apple.dock wvous-bl-modifier -int 0
#+END_SRC

***** Spaces
:PROPERTIES:
:ID:       A76717BD-1BF0-48D3-8E69-3A03BFE2B4A2
:END:

[[Y][Via]]

#+NAME: 77191228-16CC-4B95-A030-A5C2DF90CD50
#+BEGIN_SRC shell
# Don’t automatically rearrange Spaces based on most recent use
defaults write com.apple.dock mru-spaces -bool false
# Set edge-dragging delay to 0.7
defaults write com.apple.dock workspaces-edge-delay -float 1.0
#+END_SRC

***** Mouse
:PROPERTIES:
:ID:       319EDC92-B863-4D2E-A951-8479F9171FFF
:END:

Reasonably fast.
#+NAME: 9B804905-E9D0-43BE-8106-DC53009C58C4
#+BEGIN_SRC shell
defaults write 'NSGlobalDomain' com.apple.mouse.scaling -float 2
#+END_SRC

***** Terminal
:PROPERTIES:
:ID:       20C7C795-5C0A-442A-9D0F-669D1637A1D2
:END:

Only use UTF-8 in Terminal.app.
#+NAME: 9AF4BB62-76D4-4943-88FC-704A7BA492AC
#+BEGIN_SRC shell
defaults write com.apple.terminal StringEncodings -array 4
#+END_SRC

***** Activity Monitor                                                            #
:PROPERTIES:
:ID:       D36D6B69-54DC-4666-AB48-731A2FA7130F
:END:

Show the main window when launching Activity Monitor.
#+NAME: BC6F1328-5EA2-4B1D-AC72-654D829BDB31
#+BEGIN_SRC shell :results output silent
defaults write com.apple.ActivityMonitor OpenMainWindow -bool true
#+END_SRC

Visualize CPU usage in the Activity Monitor Dock icon.
#+NAME: 81FD865B-E76D-4873-8C12-42C6194AB300
#+BEGIN_SRC shell :results output silent
defaults write com.apple.ActivityMonitor IconType -int 5
#+END_SRC

Show all processes in Activity Monitor.
#+NAME: F02FC4BB-0B04-4B8A-965C-71B181139FC8
#+BEGIN_SRC shell :results output silent
defaults write com.apple.ActivityMonitor ShowCategory -int 0
#+END_SRC

Sort Activity Monitor results by CPU usageefaults write com.apple.ActivityMonitor Sort.Column -string "CPUUsage".
#+NAME: C2C6F54C-D4B7-4CBE-AF80-E45CE40C9A54
#+BEGIN_SRC shell :results output silent
defaults write com.apple.ActivityMonitor SortDirection -int 0
#+END_SRC

* Guest Configuration
:PROPERTIES:
:ID:       2A536BBD-5CF0-43B8-A87C-9E2260ADE2F5
:END:
** Base (09d89d)
:PROPERTIES:
:ID:       33FE2B6C-EE9E-407E-96C3-41675669C9AE
:END:

- Configured with a =sysop= like above
- Unprovisioned
- Used for quickly cloning for user for anything

**** Steps
:PROPERTIES:
:ID:       CC55FA18-ADF8-4FE2-AA8E-477A3449F86F
:END:

- Obtain the OS X Installer via the App Store
  - Can do this on a Mac or in a VM of a prior version of OSX
  - Back it up to both =External:Storage= and =Host:Storage=
- Start VMWare Fusion, click File \rarr New, the "Select the Installation Method"
  dialog appears
- Create a new machine by dragging the OS X Installer onto the dialog
- Continue
- Default configuration don't change anything
  - 40GB HD, 2 CPU, 2GB RAM seems fine and allows you to have another VM
    running for notes during configuration
  - Assuming that 40GB will be enough to allow OS updates as they occur over
    the lifetime of the operating system
  - Full-Clones will configure the machine in unique ways not worth capturing
    here
- Click Finish
  - Name it "El Capitan - Base (09d89d)" and leave all of the default machine configuration
    alone
- Installation takes 20m every time
  - Installer reports "35s remaining" accurately, and then 0s remaining
    inaccurately, and sits there for about 5 minutes
  - Then it reports 20m remaining, and completes in 15m
  any personal information or configuration
- Set up box and create =sysop=, don't configure, don't provision:
  - Use the name =sysop= and password =sysop=
  - Don't do it like you set up the host
  - Don't provision or customize anything
  - Don't set up printers or resolution
  - Just create the account and do nothing more
- Shutdown

**** Snapshots
:PROPERTIES:
:ID:       7DB397B7-D0EC-4AD1-9BC8-3B80452D8890
:END:

***** First Run (d0a475)
:PROPERTIES:
:ID:       9F90A8E9-E4B3-486D-A9BD-243EF10CEAF1
:END:

- Installed, created user, shutdown
- This was the first run

** Personal (3a546a)
:PROPERTIES:
:ID:       E6395620-7A49-4FEC-9E06-15B27C1FC21C
:END:

*** Base (3d4a52)
:PROPERTIES:
:ID:       0B390891-5510-4703-97D7-29949F3D4436
:END:
**** Plan
:PROPERTIES:
:ID:       0967F184-B4A0-4B24-AB0D-5D3E95C3BB13
:END:
- *Full-Clone of 09d89d*
  - Right Click d0a475 \rarr Create Full Clone\ldots
  - Named "El Capitan - gcr (3a546a)"
- Machine config
  - Processors
    - 3 cores
    - 6144 RAM
    - Enable hypervisor
    - Enable code profiling
  - Hard Disk
    - 250.00 GB HD
  - Sharing
    - =Host:Storage=
- Start the VM
- Resize the disk
  - Note that on a real Mac you can't resize a partition that OS X has
    booted from so you might boot from the Recovery Parittion to perform
    the resize instead. This doesn't work on the VMWare drive. If you try it,
    it will fail for a couple of reasons like "The partition is not journaled"
    or "The operation filed". Instead, boot into the OS and resize the partition
    there.
  - Start Disk Utility
  - Choose VMWare Virtual SATA Hard Drive Media
  - Click "Partition"
  - Look at it to get a sense of the space for the main partition and what is
    actually available
  - Close Disk Utility
  - Read [[https://themacwrangler.wordpress.com/2015/10/21/resizing-el-capitan-mac-volumes-under-vmware-fusion/][this]] for a reference
  - Open Terminal
  - Execute:
    #+NAME: 1C325C18-9A6B-4A33-A969-42CC4DBE0598
    #+BEGIN_SRC sh
    sudo diskutil resizeVolume / R
    #+END_SRC
  - View the results, they should be what you expect
  - Verify in Disk Utility
- Change =sysop= password
- Install VMWare Tools
  - In El Capitan, the display driver works correctly so you can set any
    resolution via VMWare Fusion. You can verify in the VM.
- Provision this machine
  - Use the UUID
- Perform the "Manual Steps" setup for the sysop user on this box just like the
  host
  - The host =sysop= instruction note things unique to the host and guest
- Provision =sysop=
- Create, login as, perform the "Manual Stes", and provision =gcr=,
  log out and in again
- Install software updates via App Store
- Shutdown

*** Xcode (39e716)
:PROPERTIES:
:ID:       87802E09-F643-468B-819B-3C8EEB2D3E09
:END:

Downloading Xcode takes a long time so snapshot it.

**** Plan
:PROPERTIES:
:ID:       4688E28F-F55F-444F-96DF-CDE4CED3C08D
:END:

***** Little Snitch
:PROPERTIES:
:ID:       19ACB164-B255-4F8D-916D-557975884C1C
:END:

Manually install and license it. Required to track download activity and speed.

The App Store reports downloade status under "Purchased".

***** Install XCode
:PROPERTIES:
:ID:       1094C0BB-F13F-4D43-8AAF-3432E8A9BB95
:END:

I want Xcode. I want the CLT. I want the IDE and more. Everyone
seems to be happy when you install in that order.

Go to the App Store and install Xcode.

You must start Xcode and agree to its licensing. Afterwards, close it.

***** Install CLT
:PROPERTIES:
:ID:       6164B479-E80F-4506-A4E5-DC5ABFBD3F81
:END:

Now install the CLT. Choose *Install*.

#+NAME: E0FB4DC2-E07D-4462-A997-99E112066E37
#+BEGIN_SRC shell
xcode-select --install
#+END_SRC

*** VC/Shell (283c98)
:PROPERTIES:
:ID:       C31C9412-2922-4E4A-80BB-20749A95D742
:END:

Configuring Git, the working copies, and support tools takes a long time so
snapshot it. I don't want to have =.profile= defined two places, so I define two
of them in this document and rename them when I deploy the system. Since I had
Git, I configured the Terminal after checking out a working copy for it. I
checked out all of the projects that I'm likely to use because this and the
next section are closely related. I don't consider the system usable until
installing and configuring EMACS.

**** Plan
:PROPERTIES:
:ID:       C39854E4-8FA7-42AF-9DDC-E62A96123965
:END:
***** Bash
:PROPERTIES:
:ID:       223C4BB3-2F4D-418C-93B4-8AFF0801BD43
:END:

[[http://clubmate.fi/upgrade-to-bash-4-in-mac-os-x/][Via]]. Run this by hand. Restart Terminal.

#+NAME: ADE3737D-A638-4BBD-9DD5-C42681EA1C0D
#+BEGIN_SRC shell
brew install bash
sudo bash -c 'echo /usr/local/bin/bash >> /etc/shells'
chsh -s /usr/local/bin/bash
echo $BASH_VERSION
#+END_SRC

***** Brew and BrewCask
:PROPERTIES:
:ID:       571FE633-5DC4-411B-8B5C-62F572125326
:END:

Install both.

Brew is [[http://brew.sh][here]].

BrewCask is [[http://caskroom.io][here]].

***** Java
:PROPERTIES:
:ID:       F0B50014-1E62-4182-9628-CA5EC737B41A
:END:

#+NAME: 41DCC7AD-FC9C-4EF5-9A1A-A43C22991B3D
#+BEGIN_SRC shell
brew cask install java
#+END_SRC
***** Fonts
:PROPERTIES:
:ID:       03993E03-45DF-498A-B197-283C61313E39
:END:

These could be used by any app; but they are defined specifically for use by
Emacs later on. DeltaWalker uses DejaVuSans Mono for example.

Add the font tap.

#+NAME: F39B442C-E329-4604-8A1A-EF4681A6AC31
#+BEGIN_SRC shell
brew tap caskroom/fonts
#+END_SRC

Install them automatically.

#+NAME: 59BFD86F-ED4D-4D50-85CC-BDE92854E153
#+BEGIN_SRC shell
brew cask install font-dejavu-sans
brew cask install font-quivira
brew cask install font-noto-sans
brew cask install font-noto-sans-symbols
#+END_SRC

Download and install
- Symbola

Steps to install them:
- Extract them
- Start Font Book
- Drag the top-level directory into the collection "All Fonts"
  - Font Book will search through it recursively for fonts and add them
- Automatically correct any resolution issues, which happen every time so far

***** Deltawalker
:PROPERTIES:
:ID:       D8E6483D-FF38-4A25-BA43-3CA7516B8789
:END:

#+NAME: 82653612-8AFE-4FF7-86D8-921DDA662EB9
#+BEGIN_SRC shell
brew cask install deltawalker
#+END_SRC

Got to it's Cellar location and drag it into Applications.

License it.

Set up the "Compare with DeltaWalker.workflow" by following the directions
- Copying it to the user library
- Opening it in Automator by double clicking it in Finder

- Set preferences for new comparisons (be sure of this, easy not to)
  - General
    - Date formatting: English (United States)
    - Max available memory: 1024
    - [X] Automatically find new updates and notify me
    - Colors and Fonts
      - Basic::Text Font and Text Editor Block Selection Font: DJSM 14
      - Differences::Font: DJSM 14
  - All Comparisons
    - [ ] Use text differencing optimized for speed
    - [X] Use text differencing optimized for accuracy
    - [X] Follow symbolic links
    - [ ] Ignore differences in whitespace
      - Want to know about tabs versus spaces
    - [ ] Ignore differences in character case
      - Interesting but default do care
    - [X] Ignore differences in line endings (CF and LF)
      - Most systems don't care

There are files to test with [[/opt/homebrew-cask/Caskroom/deltawalker/2.1.2/Extras/samples%0A][here]]. Test them using the Finder integration.

After Git it set up, test it there ,too.

***** Profile
:PROPERTIES:
:ID:       214656DF-ED9E-43B6-9E77-71BB88E6BC9C
:END:

#+NAME: pbod1
#+BEGIN_SRC sh
export PS1='\u@\h:\w> '
export HOMEBREW_NO_EMOJI=1
export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home"
#+END_SRC

#+NAME: ppathpre
#+BEGIN_SRC sh
/usr/local/bin
#+END_SRC

#+NAME: ppathpost
#+BEGIN_SRC sh
$JAVA_HOME/bin:$PATH
#+END_SRC

#+NAME: 25086576-D16D-45F4-9141-1A45E2C8F8FD
#+BEGIN_SRC shell :tangle ./profile-vc :noweb yes :comments no
<<pbod1>>
export PATH=<<ppathpre>>:<<ppathpost>>
#+END_SRC

***** Git Setup
   :PROPERTIES:
   :tangle:   git.sh
   :comments: no
   :ID:       5CA6B1A3-079D-4D1E-A20A-DFC8E19A68CD
   :END:

This script is *not* idempotent.

This script is set up to me. To customize it just search and replace on:
- gcr@wisdomandwonder.com :: your email address for your SSH key
- orion :: the host name where this key lives
- gcr :: your username using this key
- =orgion_gcr_rsa= :: the name of your key used for Git
- github-grettke :: your SSH alias for Github
- bitbucket-grettke :: your SSH alias for Bitbucket

Execute it to perform all of the steps.

Aggressively debug.

#+NAME: B807D882-CDAB-4029-9FFE-FB967D0DB38F
#+BEGIN_SRC sh
set -x
#+END_SRC

Install git; don't use the built-in.

#+NAME: 681F11A6-332E-424B-B878-CEF576BAAD1D
#+BEGIN_SRC sh
brew install git
#+END_SRC

Generate the key. There is no passphrase.
#+NAME: 41FF7AA3-8273-4281-A7E8-C60B048723D4
#+begin_src sh
mkdir ~/.ssh
cd ~/.ssh
ssh-keygen -N '' -t rsa -C "gcr@wisdomandwonder.com" -f orion_gcr_rsa
#+end_src

Set permissions so that =ssh= will run.

#+NAME: 298B36CF-28A0-45CC-BACF-787EAB06F348
#+begin_src sh
chmod 600 ~/.ssh/orion_gcr_rsa
chmod 600 ~/.ssh/orion_gcr_rsa.pub
ssh-add -K ~/.ssh/orion_gcr_rsa
#+end_src

OSX creates this directory everywhere and it must be ignored.
#+NAME: F17E2D3C-13C1-4E89-8BB7-DD2276BE9D21

#+NAME: 53F16E84-34DC-48D1-998C-B9214B32AD1E
#+begin_src sh
echo .DS_Store >> ~/.gitignore_global
git config --global core.excludesfile ~/.gitignore_global
#+end_src

Add they key to Bitbucket and Github.

#+NAME: 3934CA71-20AE-4136-AB57-1DEF8EBC0ADB
#+begin_src sh
cat ~/.ssh/orion_gcr_rsa.pub | pbcopy
read -p "The new key is in your clipboard. Go and add this key to BitBucket and GitHub. When you are finished, hit [enter] to continue."
#+end_src

Set up ~/.ssh/config.

#+NAME: 70D5D9F2-6CFC-4FB5-BC45-416B4ABA029F
#+begin_src sh
cat > ~/.ssh/config << EOF
Host github-grettke
     HostName github.com
     User git
     PreferredAuthentications publickey
     IdentityFile ~/.ssh/orion_gcr_rsa.pub
Host bitbucket-grettke
     HostName bitbucket.org
     User git
     PreferredAuthentications publickey
     IdentityFile ~/.ssh/orion_gcr_rsa.pub
EOF
#+end_src

Test each one out.

#+NAME: 07933181-5F02-43CB-9DF8-232DA213E4BB
#+begin_src sh
ssh -T github-grettke
read -p "Did it work? If not, fix it."
#+end_src

Separate them to allow for easier copy-pasting.

#+NAME: 66DAC891-FB97-48A8-9C8B-0292095F13A6
#+begin_src sh
ssh -T bitbucket-grettke
read -p "Did it work? If not, fix it."
#+end_src

Set up my preferences.

#+NAME: C85D0036-9DDA-4786-9621-470FB418BBD6
#+begin_src sh
git config --global user.name "Grant Rettke"
git config --global user.email gcr@wisdomandwonder.com
git config --global core.editor vi
git config --global color.ui true
git config --global core.autocrlf
git config --global alias.st status
git config --global alias.ci commit
git config --global alias.dt difftool
git config --global alias.mt mergetool
git config --global diff.tool deltawalker
git config --global difftool.deltawalker.cmd '/Applications/DeltaWalker.app/Contents/MacOS/git-diff $LOCAL $REMOTE'
git config --global difftool.prompt false
git config --global merge.tool deltawalker
git config --global mergetool.deltawalker.cmd '/Applications/DeltaWalker.app/Contents/MacOS/git-merge $LOCAL $REMOTE $BASE $MERGED'
git config --global mergetool.keepBackup false
#+end_src

Check out projects to get basic stuff working.

#+NAME: 5BD1669B-8E2A-46B5-AB80-88DA5764DEEB
#+begin_src sh
mkdir -p ~/git/bitbucket
mkdir -p ~/git/github
mkdir -p ~/git/github-anon
mkdir -p ~/src
cd ~/git/bitbucket
git clone bitbucket-grettke:grettke/list.git
git clone bitbucket-grettke:grettke/resume.git
git clone bitbucket-grettke:grettke/notes.git
git clone bitbucket-grettke:grettke/signature.git
git clone bitbucket-grettke:grettke/grant-personal.git
git clone bitbucket-grettke:grettke/correspondence.git
cd ./correspondence
ln -s ../signature/GCR-PixelMator-PNG-Export.png GCR-PixelMator-PNG-Export.png
cd ..
git clone bitbucket-grettke:grettke/texmf.git
cd ~/git/github
git clone github-grettke:grettke/osx-provision.git
cd ~/git/github-anon
git clone https://github.com/tomislav/osx-terminal.app-colors-solarized.git
cd ~/src
git clone github-grettke:grettke/help.git
#+end_src

Test DeltaWalker integration.

***** Terminal
:PROPERTIES:
:ID:       7B07A9E3-061F-4298-BF78-6B0245551995
:END:

Select the Solarized dark theme. It is checked out in Github-Anon. Go into
preferences, choose it, and set it as the default.

Set the font to DJSM 17.

*** Writing (8ef276)
:PROPERTIES:
:ID:       EFF4453A-BB19-4841-9472-D8A89700CE06
:END:
******* Plan
:PROPERTIES:
:ID:       2FE33595-5B40-44C1-BD73-CE07C7211561
:END:
**** Install via the app store
:PROPERTIES:
:ID:       35649D7F-575E-40CB-9BD5-0E19F1E72947
:END:
***** Growl
:PROPERTIES:
:ID:       5CE4AAF3-E82F-47E0-9F49-F65CECE1C838
:END:

- Start it
- enable run on login
- top left corner
- crystal

**** Emacs and supporting apps
:PROPERTIES:
:ID:       F4DF417B-AB87-49B5-B26D-B202C1F98640
:END:

Run the script or paste it in.

It should be idempotent.

The =xquartz= installer takes 5 minutes.

#+NAME: 34E00A11-AB89-4C94-B52E-7B4C94401252
#+BEGIN_SRC sh :tangle ./install-emacs-and-stuff.sh
brew cask install xquartz
read -p "Review the installation. Press return to continue."
brew cask install growlnotify
read -p "Review the installation. Press return to continue."
brew install ccrypt
read -p "Review the installation. Press return to continue."
brew install aspell -all
read -p "Review the installation. Press return to continue."
brew install imagemagick --with-fftw --with-fontconfig --with-webp --with-x11
read -p "Review the installation. Press return to continue."
brew install emacs --with-cocoa --with-gnutls --with-imagemagick
read -p "Review the installation. Press return to continue."
brew install graphviz
read -p "Review the installation. Press return to continue."
brew install pandoc
read -p "Review the installation. Press return to continue."
brew linkapps
#+END_SRC

Note:
#+BEGIN_QUOTE
==> ./configure --prefix=/usr/local/Cellar/emacs/24.5 --enable-locallisppath=/usr/local/share/emacs/
==> make
==> make install
==> Caveats
A command line wrapper for the cocoa app was installed to:
  /usr/local/Cellar/emacs/24.5/bin/emacs

To have launchd start emacs at login:
  mkdir -p ~/Library/LaunchAgents
  ln -sfv /usr/local/opt/emacs/*.plist ~/Library/LaunchAgents
Then to load emacs now:
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.emacs.plist
.app bundles were installed.
Run `brew linkapps emacs` to symlink these to /Applications.
==> Pouring pandoc-1.15.2.1.el_capitan.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
#+END_QUOTE

****  Install Org Mode and supporting stuff per HELP
:PROPERTIES:
:ID:       63AFF6C1-2214-44F2-9069-BA156C1D322E
:END:

This script should be idempotent.

#+NAME: 916D6512-03E7-4971-8BAC-53D6FA258BBD
#+BEGIN_SRC shell :tangle ./org-and-stuff.sh
set -x
rm -rf ~/src/org-mode
rm -rf ~/src/org2blog
rm -rf ~/src/use-package
cd ~/src
git clone git://orgmode.org/org-mode.git
cd org-mode
emacs -batch -Q -L lisp -l ../mk/org-fixup -f org-make-autoloads
cd ~/src
git clone github-grettke:punchagan/org2blog.git
cd ~/src
git clone https://github.com/jwiegley/use-package.git
#+END_SRC

**** EELIB
:PROPERTIES:
:ID:       65AD0341-DCA6-42E8-9768-3DA41A274F8F
:END:

- Make a directory =~/EELIB=
  #+NAME: 19FF07B8-3DFE-4CC4-9ABA-9BED5C430F02
  #+BEGIN_SRC shell
  mkdir ~/EELIB
  #+END_SRC
- Download the following JAR files to that folder
- [[http://plantuml.com/][PlantUML]] to it, either downloading the unversioned JAR or
   renaming it to "plantuml.jar"
- [[http://ditaa.sourceforge.net/][ditaa]] to it, extract the versioned JAR, and rename it to "ditaa.jar"
- [[https://www.languagetool.org/][LanguageTool]]
  - Use the "daily build" if the download is too slow
  - Extract it here
  - Rename the directory to "LanguageTool"
  - Took 8 tries to download it; kept stalling at 80%

**** Profile
:PROPERTIES:
:ID:       D0B61BD6-13D8-4569-8696-30256456A05C
:END:

Now everything is in place for the new profile. The new profile is required
to continue installation

#+NAME: B2E241B5-2075-4CD8-BF41-C0D22FAE8233
#+BEGIN_SRC shell :tangle ./profile-final :noweb yes :comments no
<<pbod1>>
export INFOPATH='/usr/local/share/info:/usr/share/info'
export CCRYPT="/usr/local/Cellar/ccrypt/1.10/share/emacs/site-lisp"
export EELIB="/Users/$(whoami)/EELIB"
export MACTEX_BIN="/usr/local/texlive/2015/bin/x86_64-darwin"
export PATH=<<ppathpre>>:$MACTEX_BIN:<<ppathpost>>
alias e='open /Applications/Emacs.app --args --debug-init'
alias ec='/usr/local/Cellar/emacs/24.5/Emacs.app/Contents/MacOS/Emacs -nw --debug-init'
#+END_SRC

Source it or start a new shell or run this; it should be idempotent.

#+NAME: 4E3EF76D-AD57-40C5-B9D6-CC9080576293
#+BEGIN_SRC shell :tangle ./new-profile.sh :comments no
set -x
rm ~/.profile
cp /Volumes/VMware\ Shared\ Folders/Storage/wip/profile-final ~/.profile
. ~/.profile
cat ~/.profile
#+END_SRC

Can't test MacTeX yet.

**** MacTex & GnuPlot
    :PROPERTIES:
    :ID:       4769C0C6-AA8F-4073-B233-253691004873
    :header-args: :tangle ./mactex-gnuplot.sh
    :END:

This is 2.4 GiB. That is not much. If you get the US mirror it is 20 minutes or
2 hours. The Torrent is a better option.

Read the installation directions and install it.

- Update your installation for OS X 10.11 via
  https://tug.org/mactex/UpdatingForElCapitan.pdf
  - Updated the texlive utility to point in the right place, it was at 1.21,
    fix is in 1.23
    #+BEGIN_QUOTE
    For previous versions of TEX Live Utility Open TEX Live Utility Preferences
    and click on the Choose. . . button as in Figure (4). That opens a file
    chooser. Type Shift-Cmd-G, enter ~/Library/TeX~ into the dialog box as shown in
    Figure (5) and then press Return. Finally Double-Click on ~texbin~.
    #+END_QUOTE

- tex live utility
  - Set paper size

From here either use the script which should be idempotent or copy and paste.

Set up my TeX stuff for KOMA-script. Backup the default configuration first.

#+NAME: F70EC578-023C-45CD-A584-F00AE7D33400
#+begin_src sh
set -x
ls /usr/local/texlive/2015
sudo cp /usr/local/texlive/2015/texmf.cnf /usr/local/texlive/2015/texmf.cnf-`date '+%Y_%m_%d__%H_%M_%S'`
ls /usr/local/texlive/2015
sudo tlmgr conf texmf TEXMFHOME ~/git/bitbucket/texmf/
#+end_src

Check that the path is really updated.

#+NAME: 34890901-8E9D-46E5-9738-2718CD26908E
#+begin_src sh
kpsewhich KomaDefault.lco
#+end_src

The documents say to maybe do the following. I did it.

#+NAME: 008DCE01-EE0D-4A96-93A5-7B6E91D7C951
#+begin_src sh
sudo mktexlsr
#+end_src

***** Install GNUPlot
:PROPERTIES:
:ID:       F66605AC-4989-481C-986A-2879A7F32F33
:END:

Once that is installed, install gnuplot.

#+NAME: FB8E0242-CDD6-45E4-86A7-10871990595A
#+begin_src sh
brew install gnuplot --with-latex --with-pdflib-lite --with-test --with-x11
#+end_src

Note:
#+BEGIN_QUOTE
==> Pouring lua-5.2.4_1.el_capitan.bottle.tar.gz
==> Caveats
Please be aware due to the way Luarocks is designed any binaries installed
via Luarocks-5.2 AND 5.1 will overwrite each other in /usr/local/bin.

This is, for now, unavoidable. If this is troublesome for you, you can build
rocks with the `--tree=` command to a special, non-conflicting location and
then add that to your `$PATH`.
#+END_QUOTE

**** Dotfiles
:PROPERTIES:
:ID:       6B76A015-45CC-4FB7-B075-0D3DDA2C22EA
:END:

This script should be idempotent.

Link Emacs dot files to their implementation.

#+NAME: C86B35D4-0009-499F-A779-5E148FF231FB
#+BEGIN_SRC sh :tangle ./link-emacs-dotfiles.sh
rm ~/.emacs.el
ln -s ~/src/help/.emacs.el ~/.emacs.el
rm ~/.aspell.en.pws
ln -s ~/git/bitbucket/list/.aspell.en.pws ~/.aspell.en.pws
rm ~/.aspell.en.prepl
ln -s ~/git/bitbucket/list/.aspell.en.prepl ~/.aspell.en.prepl
rm -rf ~/.emacs.d
mkdir ~/.emacs.d
ln -s ~/src/help/eshell/ ~/.emacs.d/eshell
#+END_SRC
**** Test stuff out: using HELP and help.org
:PROPERTIES:
:ID:       B1B9A22B-578D-4DFA-9A8A-803AB11A8D0D
:END:

- [X] Get Emacs running
  - Usually problems with package loads
    - EG dimnish, =list-package= and install it and restart
    - =lexbind-mode= refuses to install
      - "Symbol's function definition is void: lexbind-mode"
      - Start with =--no-init= and comment out =lexbind-mode= just to get Emacs
        set up, then install =lexbind= via the package manager, then add it
        back in
    - Broken Org-Mode
      - This checks out Org-Mode from the trunk. Sometimes stuff get's
        broken. My config debugs on error. The goal is to always have
        a working system. Sometimes, I copy over a working copy of Org
        or any of the libraries onto the host if there are issues.
- [X] tangle
  - Tangle the document successfully
- [X] execution
  - Delete every result block: just do it manually search for =#+RESULT=
  - Delete all image output
  - Execute entire document successfully
  - Images re-appear
- [X] eshell
  - Run it
  - Emacs uses correct HELP directory
- [X] ccrypt
- [X] ispell
- [X] weasel words
- [X] langtool
  - Verify installation, can have the wrong dir and the tool just says that
    there are no issues
  - Run =langtool-check-buffer=
  - qkc does the scan, qkC suggests corrects, verified on a corresponsence
- [X] Correspondence
  - Pick a letter
  - Address and signature and everything looks right
- [X] Messages
  - Make sure that there are no startup warnings or issues
- [X] Export to everything
  - Longest test
  - This is used for publishing
  - First delete everything
  - [X] html
    - Images are links, not images
  - [X] md
    - Images are links, not images
  - [X] pdf
  - [X] txt
